@startuml
autonumber
actor User    

box "Margined Protocol" 
    participant engine    
    collections vamm     
    participant "insurance fund" as insurance    
    participant "fee pool" as pool    
end box

box "External"
    collections "Eligible Collateral" as cw20
end box


title Open Position (Long)

== Engine checks ==

User -> engine : open_position(\n\tquote_asset_amount\n\tleverage\n)
activate engine

engine -> engine : require(margin_ratio >= initial_margin_ratio)

== Swap Input ==

Group is_increase
    engine -> vamm : swap_input(\n\tquote_asset_amount\n)
    activate vamm

    vamm -> vamm: get_input_price(\n\tquote_asset_amount\n)
    vamm -> vamm: update_reserves()

    vamm -> engine: return price
    deactivate vamm
end

== Process Reply ==
Group reply

    engine -> engine: update_open_interest_notional()
    engine -> engine: update_position

    Group transfer_fees()
        engine -> cw20 : transfer margin + fees
        cw20 -> pool : transfer fees
        cw20 -> insurance : transfer fees
    end 
end

engine -> User : Tx Receipt
deactivate engine

@enduml
