@startuml openPos
actor       User       
boundary    Boundary    
control     Control     
entity      Entity      
database    Database    
collections Collections 
queue       Queue       
User -> Boundary : To boundary
User -> Control : To control
User -> Entity : To entity
User -> Database : To database
User -> Collections : To collections
User -> Queue: To queue
@enduml
