@startuml removeMargin
participant Participant
actor       Actor       
control     Control     
entity      Entity      
database    Database    
collections Collections 
queue       Queue       
Participant -> Actor : To actor 
Participant -> Contract1 : To boundary
Participant -> Control : To control
Participant -> Entity : To entity
Participant -> Database : To database
Participant -> Collections : To collections
Participant -> Queue: To queue
@enduml
